name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_OPTIONAL: 'false'

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      # try a ci install without optional deps; fallback to no-optional if needed
      - name: Install dependencies
        run: npm ci --omit=optional || npm ci --no-optional || npm install --no-optional
      - name: Build
        run: npm run build